import Header from '@/components/Header'
import './globals.css'
import Providers from './Providers'
import Navbar from '@/components/Navbar'
import Modal from '@/components/modal/Modal'
import getCurrentUser from '../actions/getCurrentUser'


export const metadata = {
  title: 'IMDB',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png',
  },
}

export default async function RootLayout({ children }) {
  
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body>
        <Providers>
          <Modal/>
          <Header currentUser={currentUser}/>

          <Navbar/>
          
          {/*Searchbo */}

          
          {children}
        </Providers>
      </body>
    </html>
  )
}
